if: branch = master
language: node_js
node_js:
  - 10
before_script:
  - yarn
script:
  - yarn lint
  - yarn test
deploy:
  provider: npm
  email: antonionetocardoso@hotmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    branch: master
deploy:
  provider: surge
  project: ./src/interface/anchor/sample/
  domain: ovo-anchor.surge.sh
  skip_cleanup: true
  on:
    branch: master
